## Asignación de variables

In [4]:
x ,y = 1, 2

print(x)
print(y)

1
2


## Sobrescribir valores con la misma variable

In [8]:
x=5

x=x+3  #Toma el valor anterior y despues lo actualiza a su nuevo valor
x

8

## Estructuras de datos

### - Cadenas de texto

Una cadena es una secuencia de caracteres, como "Hola Mundo". Las cadenas están rodeadas por comillas simples o dobles. Podríamos usar la función de print para enviar las cadenas a la pantalla.

In [9]:
print("Hola mundo")

Hola mundo


### Función type() y la función len()

Tambien se pueden asignar cadenas a variables, por ejemplo:

In [ ]:
g="Hello world"  
l='How are you?'

#Podemos saber que tipo de dato es con la función type()
print(type(g))
print(type(l))

#Podemos saber además la longitud de la cadena con la funcion len()
#La cadena comnienza desde la posicion 0. NOTA: Los ESPACIOS cuentan como caracter
print(len(g))
print(len(l))

<class 'str'>
<class 'str'>
11
12


### Acceder a un caracter especifico de la cadena o a un conjunto de caracteres

Podemos acceder a cualquier posicion de la cadena, colocando la variable donde se guardo la cadena y el valor de la posicion que deseamos obserar, por ejemplo:

In [19]:
print(g[4])
print(l[8])

o
y


También podríamos seleccionar una secuencia usando el segmento de cadenas. Por ejemplo, si queremos obtener el "World", podríamos hacer el siguiente comando:

In [21]:
print(g[6:11])

world


### Unir dos o más cadenas

In [1]:
str_a = "I love Python! "
str_b = "You too!"

print(str_a + str_b)

I love Python! You too!


# -Listas

In [3]:
# Sintáxis

list_a=[1,2,3]
print(list_a)

[1, 2, 3]


In [4]:
list_b=["hello", "world", "python"]
print(list_b)

['hello', 'world', 'python']


Se pueden combinar varios tipos de datos en la lista

In [6]:
lista_c=[1, "hello", 3.14, [1,2,3]]
print(lista_c)

[1, 'hello', 3.14, [1, 2, 3]]


Podemos mandar a llamar a los elementos de la lista

In [11]:
lista_c[2]


3.14

In [12]:
lista_c[0]


1

In [13]:
lista_c[1]

'hello'

Podemos de la misma forma saber la longitud de la cadena

In [14]:
len(lista_c)

4

Podemos unir listas o como mayormente se les dice: concatenar listas

In [15]:
list_a+list_b

[1, 2, 3, 'hello', 'world', 'python']

### Agregar más elementos al final de la lista con la función .append()

In [17]:
list_a.append(4)
print(list_a)

list_a.append("june")
print(list_a)


[1, 2, 3, 4, 4]
[1, 2, 3, 4, 4, 'june']


### Insertar un elemento en algun lugar en especifico de la lista con la función .insert()

In [24]:
"""El primer argumento es la posición donde se insertará el 
nuevo elemento, y el segundo
argumento es el elemento que se desea insertar."""

list_a.insert(1, "start") 
print(list_a)

#esta cadena se actualiza a su nuevo valor, reordenando
#los elementos a su derecha
#El reusltado muestra diferentes posiciones de start,
#porque se inserta en la posición 1 cada vez.

[1, 'start', 'start', 'start', 'start', 'start', 'start', 'start', 2, 3, 4, 4, 'june']


### Eliminar un elemento con la función del

In [26]:
del list_a[11]
list_a

[1, 'start', 'start', 'start', 'start', 'start', 'start', 'start', 2, 3, 4]

### Truco. Convertir una cadena de texto en tipo lista

In [27]:
list("Hello world")

['H', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']

# -Tuplas

Se parecen a las listas sin embargo, las tuplas son inmutables y suelen contener una secuencia heterogénea de elementos a los que se accede mediante desempaquetado (véase más adelante en esta sección) o indexación (o incluso por atributo en el caso de las tuplas con nombre). Las listas son mutables y sus elementos suelen ser homogéneos y se acceden iterando sobre la lista.

In [1]:
tuple_1 = (1, 2, 3, 2)
tuple_1

(1, 2, 3, 2)

In [2]:
# PEDIR LA LOGNITUD DE LA TUPLA
len(tuple_1)

4

Podemos contar la ocurrencia en la que se se repite un elemento con el siguiente comando:

In [3]:
tuple_1.count(2)

2

Existen tambien los conjuntos y los diccionarios. A medida que vayamos avanzanco los iremos implementando

# **Introduccioón a los arrays de Numpy**

Para crear arreglos a traves de numpy se utilizan los siguiente comandos:. Estos son ideales si deseamos representar matrices:

In [ ]:
import numpy as np

#areglo unidimensional 

x=np.array([1,2,3])
print(x)

[1 2 3]


Si deseamos agregar más arreglosm, debemos agregar otros corchetes 

In [9]:
y=np.array([[4,5,6],[1,2,3]])
y

array([[4, 5, 6],
       [1, 2, 3]])

Muchas veces necesitamos conocer el tamaño o la longitud de una matriz.

- El atributo `shape` se aplica a una matriz M y devuelve una matriz de 2 × 3, donde el primer elemento es el número de filas de la matriz M.

- El segundo, el número de columnas. Cabe destacar que el resultado del atributo `shape` es una tupla. El atributo `size` se aplica a una matriz M y devuelve el número total de elementos de la matriz M.


In [ ]:
# Comando para conocer el numero de filas y columnas de un arreglo
y.shape

(2, 3)

In [13]:
#Devuelve el numero de elementos que contiene la matriz
y.size

6

Con frecuencia, necesitamos generar matrices con una estructura o patrón definido. Por ejemplo, podríamos querer crear la matriz z = [1 2 3 … 2000]. Sería muy engorroso escribir la descripción completa de z en Python. Para generar matrices ordenadas y con espaciado uniforme, resulta útil usar la función `arange` de NumPy.

In [ ]:
m=np.arange(1,10)  #Asi generamos un arreglo con los numeros del 1 al 9
                    #Podemos agregar el incremento con un tercer argumento, 
                    # por ejemplo np.arange(1,10,2) para obtener los numeros impares
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
m=np.arange(1,10, 2) 
m

array([1, 3, 5, 7, 9])

A veces queremos garantizar un punto de inicio y un punto final para un array, pero manteniendo elementos espaciados uniformemente.Por ejemplo, podríamos querer un array que empiece en 1, termine en 8 y tenga exactamente 10 elementos.

- Podemos usar la función ``np.linspace``. linspace toma tres valores de entrada separados por comas. Así,

A = linspace(a,b,n)

genera un array de n elementos espaciados uniformemente, que empieza en a y termina en b.


In [21]:
A=np.linspace(0, 10, 5) #Genera un arreglo con 5 numeros equidistantes entre 0 y 10
A

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Acceder a un elemento es parecido a las listas

In [22]:
A[1]

np.float64(2.5)

In [23]:
A[-1]

np.float64(10.0)

In [24]:
A[2:]

array([ 5. ,  7.5, 10. ])

# **Ingresar a elementos de matrices de 2 columnas**

Para acceder a los elementos de una matriz de 2 columnas, es necesario llamar a la coordenada en donde se encuentra, siguiendo el siguiente comando:

In [26]:
x=np.array([[1,5,9],[3,5,7]])
x

array([[1, 5, 9],
       [3, 5, 7]])

In [30]:
x[0,2] #Rcuerda que las filas y columnas comienzan desde la posición 0, 
        #por lo que x[0,2] se refiere al elemento en la primera fila y tercera columna del arreglo x.

np.int64(9)

Podemos acceder a todo el arreglo de la columna, con el siguiente comando:

In [34]:
x[0, :]

array([1, 5, 9])

In [35]:
x[1:]

array([[3, 5, 7]])

Podemos acceder a algunas filas y columnas especificas con el siguiente comando:

In [ ]:
x[[0,1],2] #Selecciona el elemento en la tercera columna de las filas 0 y 1 del arreglo x.

array([9, 7])

In [40]:
x[:, 2] #Selecciona el elemento en la tercera columna de todas las filas del arreglo x.

array([9, 7])

# **Generación de matrices vacias**

Para crear una matriz vacía (es decir, matrices donde todos sus elementos son cero) se utiliza el siguiente comando, donde se debe especificar las filas y columnas que tendrá la matriz:

In [41]:
x=np.zeros((3,4)) #Genera un arreglo de ceros con 3 filas y 4 columnas
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Tambien podemos crear una matriz llenas de 1

In [42]:
x=np.ones((2,3)) #Genera un arreglo de ceros con 3 filas y 4 columnas
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
y=np.empty(3) #Genera un arreglo de solo ceros
y

array([4.9e-324, 9.9e-324, 1.5e-323])

# **Modificar valores de la matriz**

Para modificar el valro de un elemento de la matriz, se sobrescribira como las listas:

In [51]:
A=np.ones((4,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Se modifica de este manera:

In [52]:
A[1, 2]=6
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 6., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Podemos de igual manera modificar de un rango determinado:

In [54]:
A[1, :]=6
A

array([[1., 1., 1., 1., 1.],
       [6., 6., 6., 6., 6.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Puedes acceder dependiendo de lo que deseas. Es cuestión de ti maniuplar los arrays como desees-

# **Aritmetica de matrices**

Podemos generar operaciones entre matrices de la siguiete forma:

In [56]:
B=np.array([[1, 2, 3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
#Sumamos el valor 3 a cada elemento del arreglo B
B+3

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Restamos el valor -6 a cada elemento del arreglo B  
B-6

array([[-5, -4, -3],
       [-2, -1,  0]])

In [60]:
#Multiplicamos la matriz por 2
2*B

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [61]:
#Dividimos entre 7  
B/7

array([[0.14285714, 0.28571429, 0.42857143],
       [0.57142857, 0.71428571, 0.85714286]])

In [63]:
#Elevamos al cubo cada elemento del arreglo B
B**3


array([[  1,   8,  27],
       [ 64, 125, 216]])

De la misma forma que en algebra lineal, podemos operar matrices, solo debemos tener cuidado en que las filas y columnas sigan las reglas de las matrices para operarlas.

In [67]:
D=np.array([[1, 2], [-3, 14]])
D

array([[ 1,  2],
       [-3, 14]])

Con este comando podemos aplicar la transupesta de la matriz:

In [66]:
D.T

array([[ 1, -3],
       [ 2, 14]])

Algo increible de las matrics, es que podemos agregar condiciones logicas para operar con sus elementos, por ejemplo:

In [68]:
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [69]:
x>3 #se obtiene un arreglo de valores booleanos, donde cada elemento 
    #indica si la condición es verdadera o falsa para el elemento correspondiente en el arreglo x.

array([False, False,  True,  True,  True, False])

In [ ]:
x>y #se obtiene un arreglo de valores booleanos, donde cada elemento indica 
        #si la condición es verdadera o falsa para la comparación entre los elementos 
        # correspondientes en los arreglos x e y.

array([ True, False,  True,  True,  True, False])

##### Modficar el array x, para que sus  sus elementos sean estrictamente mayores a 3

In [72]:
x_modif=x[x>3] #se obtiene un nuevo arreglo que contiene solo los elementos de x que cumplen la condición x>3.
x_modif

array([4, 5, 9])

Podmeos agregar una condicional para sustituir elementos por un numero dterminado:

In [74]:
x[x>3]=2
x

array([1, 2, 2, 2, 2, 3])